apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: department-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/NaveedAmanat/micro-department-service-artifact.git
    targetRevision: HEAD
    path: devolpment
  destination:
    server: https://kubernetes.default.svc
    namespace: micro-service

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true


